ChangeLog
osg-import-srpm

Add a few last-minute changes to 1.7.0

---

osgbuild/main.py

Changes allow osg-build to continue working for tasks like rpmbuild,
even if `osgbuild.mock` or `osgbuild.kojiinter` are missing.
If a module is missing, options pertaining to that module will not show
up in `osg-build --help`, and it will direct the user to install the
package that contains the module. Attempting to invoke a task provided
by a missing module will cause an error and again direct the user to
install the package containing that module.

Make koji and mock optional (SOFTWARE-2671)

---

osgbuild/main.py

Also clean up some inconsistencies.

Specify default options in help text (SOFTWARE-2558)

---

osgbuild/fetch_sources.py

If using a meta URL and the repo contains a file named $name.spec (where
$name is the name of the repo), use that spec file.

Use spec file from Git repo (SOFTWARE-2962)

---

osgbuild/importer.py

I tested this by giving it an error but existing http and it worked.

SOFTWARE-2570

---

osgbuild/fetch_sources.py

This addresses some concerns found by @matyasselmeci.
In particular, say which required fields were missing, if any, and don't talk about the optional initial unnamed arguments.

provide less confusing error messages in some cases (SOFTWARE-3568)

---

osgbuild/fetch_sources.py

turns out "git fetch tagname" doesn't work on git 1.7.1, which
is what runs on our SL6 Fermi VMs.  The EL6 git version on ingwe
is slightly newer and didn't suffer from this, but alas, not all
EL6's run the same git apparently.
Anyway, first try explicitly to fetch a tag object, but do it quietly
because it's ok if it fails - then fall back to a generic fetch, so
a branch name or HEAD can be specified.  If that one fails, error out.

git-fetch compat for sl6 git 1.7.1 (SOFTWARE-3568)

---

osgbuild/importer.py

This can be turned off via the `--nosha1sum` flag but is on by default.

osg-import-srpm: add "sha1sum"s to .source files (SOFTWARE-3593)

---

koji-blame

This is a helpful option for generating IRIS-HEP quarterly metrics for past quarters

Add '--until' option

---

osgbuild/test/test_osgpromote.py

and stop pretending that `__file__` is a directory

remove offensive content

---

osgbuild/constants.py

The use case here is to make a tarball bundle that contains osg-build and everything needed to run it.

Also search under $OSG_LOCATION for data files (if they exist)

---

osgbuild/main.py

Should avoid errors with e.g. people putting their home dirs in git

Check for svn first and break if it's found

---

osgbuild/fetch_sources.py

@matyasselmeci, last year you wanted some [better] doco for these functions.
I think what happened was i wasn't wild about leaving 5 lines of comments-prose to explain two lines of code, and i said i'd [have to] sleep on it.  Well anyway, it's about time i offer you something.
Though pithy, i hope you will find these docstrings/comments explain enough to [help] make sense of these functions.

Add misc docstrings for fetch_sources 

---

data/promoter.ini
osgbuild/constants.py

Do EL8 builds and promotes by default

---

osgbuild/promoter.py

Should fix https://opensciencegrid.atlassian.net/browse/SOFTWARE-4513.

Implement `<` for Rejects

---

osgbuild/promoter.py
osgbuild/test/test_osgpromote.py

osg-promote now prints the table syntax for the new JIRA view.
osg-promote also prints out the old syntax since it's still used in a few places even if you've switched to the new view (it's used in the ticket creation and editing dialog boxes).
output:
```
JIRA code for this set of promotions (old syntax):
*Promotions*
Promoted osg-ca-certs-updater-2.0-1 to osg-3.6-el*-testing
|| Build || Tag ||
| [osg-ca-certs-updater-2.0-1.osg36.el8|https://koji.opensciencegrid.org/koji/buildinfo?buildID=14360] | osg-3.6-el8-testing |
JIRA code for this set of promotions (new syntax):
**Promotions**
Promoted osg-ca-certs-updater-2.0-1 to osg-3.6-el*-testing
**Build** | **Tag**
--- | ---
[osg-ca-certs-updater-2.0-1.osg36.el8](https://koji.opensciencegrid.org/koji/buildinfo?buildID=14360) | …
```

Support writing the new JIRA table syntax (SOFTWARE-4418)

---

osgbuild/importer.py

This deals with SRPMs that don't have the right filename.

Get SRPM name/version (we don't use release) by querying it, not parsing the filename

---

osgbuild/svn.py

It was broken for devops (the "return False" at the end should have been a "return True")
Did a bit of commenting and reorganizing to make the logic easier to see

Fix SVN branch protection checking

---

data/promoter.ini
osgbuild/constants.py
osgbuild/main.py
osgbuild/test/test_osgpromote.py
rpm/osg-build.spec

note i have not touched `osgbuild/test/test_osgbuild.py` - i don't think i understand the tests there well enough to add el9 items

Add el9 support (SOFTWARE-5342)

---

osgbuild/git.py
osgbuild/test/test_osgbuild.py

The functions borrowed from svn.py are largely the same (only small tweaks) - i don't know if it'd be better to make shared library functions for these or something, but this was the most straightforward-seeming way to implement it.
@matyasselmeci you are much more familiar with the osg-build internals, so feel free to summarily reject this and do it however you see fit - i don't want to make a mess of your codebase :)

add restricted branch checks for git (SOFTWARE-5476)

---

data/promoter.ini
osgbuild/constants.py

https://opensciencegrid.atlassian.net/browse/SOFTWARE-5609

Build and promote for EL9 as well by default for OSG 3.6

---

data/promoter.ini
osgbuild/constants.py

plus some promotion route cleanup.

osg-build changes for building for OSG 3.7 (SOFTWARE-5573)

---

osgbuild/importer.py

This lets me specify the directory in SVN to write the package files to. Useful if I want to add an .el9 suffix for example.

Add --dirname argument to osg-import-srpm

---

osgbuild/git.py
osgbuild/main.py
osgbuild/svn.py

We were apparently testing this so I think it used to work by accident. Add code to validate the branch.

Allow building from Git URLs

---

osgbuild/kojiinter.py

Fix downloading koji builds (--getfiles flags)

---

osgbuild/osg_koji.py
osgbuild/utils.py

instead of making the user rerun the program with a different flag if they want to switch.  I think this is more user friendly.

osg-koji setup: Ask for auth method

---

osgbuild/git.py
osgbuild/svn.py

(continuing when the user says no, and vice versa)

Fix reversed ask_yn() call when checking working dir

---

osgbuild/utils.py

Modify print_table() (which prints the promotion plan for osg-promote) to avoid printing a table wider than the screen.

osg-promote: Better print_table()
