opensciencegrid/osg-build

ChangeLog
osg-koji

Add the CILogon-OSG CA cert to the CA certs bundle that osg-koji setup creates. This is necessary before we can replace koji-hub's host cert with one signed by the CILogon-OSG CA. (SOFTWARE-2273)
This also moves the code which validates a downloaded cert file (checks hash and subject) into a separate function.

osg-koji setup: add CILogon-OSG CA cert to osg-ca-certs.crt

---

osg-import-srpm
osgbuild/utils.py

This triggered a major restructuring of osg-import-srpm, which had been
coming for a while.  Some highlights are:
- Create the new .source file _after_ doing the diff/extract.  The diff
is the part that's most likely to fail for some reason, so this change
keeps the dir from being in a half-merged state.
- Use normal imports instead of qualified imports, e.g.
"import os.path; os.path.abspath(...)" instead of
"from os.path import abspath; abspath(...)".
- Add the 'fedora' and 'globus' providers (for naming the .source
files).
- Extract the specific spec file instead of using *.spec.  This ends up
being safer for manipulating the spec file afterwards, though may
break if the SRPM contains multiple spec files -- something that
shouldn't happen.
- Add pushd/popd functions to utils.  These …

Add (-3) --diff3 option for a three-way diff.

---

ChangeLog
osgbuild/main.py

This changes the format of log messages from e.g.
```
INFO:osg-build:The message
```
to
```
>> The message
```

Make log messages look nicer

---

osgbuild/test/test_osgbuild.py

In the unit tests, `test_rpmbuild` started failing due to the log message format change; fix that.
`test_mock_auto_cfg` tests a broken feature (the auto-generated config references 3.1 and EL5), so remove it.  (The feature will be removed later, once I figure out the semantics for the replacement).

Fix test_rpmbuild and test_mock_auto_cfg

---

ChangeLog
osgbuild/importer.py

If `--update` (or `-U`) is specified, `osg-import-srpm` will update the `upstream/source` file as usual, and then diff3 the spec file in `osg/` if it exists.  This way, you can run `osg-import-srpm -U` on any package without having to first check if it has an `osg` dir or not.
This change will make it more likiely for people to run `osg-import-srpm` in the package directory (e.g. in `trunk/foo`); until now, `osg-import-srpm` needed to be run in the svn branch instead (e.g. `trunk`).  Handle that condition better.

Add --update option to osg-import-srpm

---

osgbuild/constants.py
osgbuild/main.py
osgbuild/srpm.py
osgbuild/test/test_osgbuild.py

Internal code fix: make the term "dver" be used consistently throughout the code. In some places, dver was the OS release with "el" before it (e.g. "el5", "el6"), and in other places, dver was just the OS release (e.g. "5", "6"). The term "dver" now means the former, and the term "redhat release" or "rhel" is used for the latter.
Some dictionaries used to be keyed by redhat release; for consistency, make them all keyed by dver instead.

Dver cleanup

---

osg-koji

For SOFTWARE-2455. Improve the confirmation messages for osg-koji setup to make it easier to use. In one case (overwriting the server cert), the remove the confirmation message.
Also provide the user with a command to test their setup.

Improve osg-koji setup UX

---

osgbuild/fetch_sources.py

This commit adds support for providing a verified git tag as a source for an RPM.
The line in the source file should have a format similar to the following:
```
{"type": "git", \
"url": "https://github.com/opensciencegrid/cvmfs-config-osg.git", \
"tag": "v0.1",
"hash": "e2b54cd1b94c9e3eaee079490c9d85f193c52249"}
```
(should be on the same line in the file; line continuations added for readability.)
This results in a tarball named `cvmfs-config-osg-v0.1.tar.gz` that:
- File contents are prefixed with directory `cvmfs-config-osg-v0.1/`
- Contents correspond to the git tag `v0.1`
- The tag `v0.1` is verified to be the same as hash `e2b54cd1b94c9e3eaee079490c9d85f193c52249` in the repository.
This provides end-to-end verification of the contents of source tarballs for git-based projects.

Add support for git repos in a RPM source

---

osg-promote
osgbuild/promoter.py

when, say, my cert has expired, that's all i need to know.  it feels
like something went spectacularly wrong when osg-promote explodes with
a traceback, even though it's really a simple and normal error.

don't dump traceback for normal errors

---

data/promoter.ini

These are the "contrib", "prerelease", and "testing" aliases, and the goc routes.

Base default promotion routes on 3.4 instead of 3.3

---

koji-blame
osg-build
osg-import-srpm
osg-koji
osg-promote
osgbuild/clientcert.py
osgbuild/error.py
osgbuild/fetch_sources.py
osgbuild/git.py
osgbuild/importer.py
osgbuild/kojiinter.py
osgbuild/main.py
osgbuild/mock.py
osgbuild/promoter.py
osgbuild/six.py
osgbuild/srpm.py
osgbuild/svn.py
osgbuild/test/test_osgbuild.py
osgbuild/test/test_osgpromote.py
osgbuild/utils.py

Add support for running osg-build and other tools using Python 3. This is more future-proofing than anything that's useful right now -- for one, RHEL 6/7 do not include Python 3 versions of yum/rpm libraries.
I've been using this for the past month or two with Python 2 so there are likely no regressions; I also tested the code on Fedora 26/27 and it works fine there, other than problems with the Koji libraries themselves (our password caching and proxy cert patches don't work on the Python 3 version of Koji).

Python 3 support

---

osgbuild/fetch_sources.py
osgbuild/test/test_osgbuild.py

If the tag contains a release number (e.g. the "-2" in "2.1-2"), chop it off and don't put it in the tarball filename. tarballs should be named `NAME-VERSION.tar.gz` and dashes aren't allowed in VERSION anyway.

Omit release numbers from the tarball name (SOFTWARE-3156)

---

osgbuild/fetch_sources.py
osgbuild/test/test_osgbuild.py

Add a new format for .source files specific to GitHub. OSG is pretty committed to GH at this point what with all our software and documentation being hosted there, so adding syntactic sugar shouldn't be a problem. The new format looks like:
```
type=github repo=opensciencegrid/cvmfs-config-osg tag=0.1 hash=e2b54cd1b94c9e3eaee079490c9d85f193c52249
```
which is a shorter version of
```
type=git url=https://github.com/opensciencegrid/cvmfs-config-osg.git tag=0.1 hash=e2b54cd1b94c9e3eaee079490c9d85f193c52249
```

type=github support for .source files

---

osgbuild/fetch_sources.py

if the expected hash matches the upstream ref, no need to dereference
them.  otherwise, dereference both (that is, until a non-tag object is
reached) and compare those.
(i am thinking that perhaps only the upstream ref needs to be
dereferenced, since it would be weird for our expected hash to refer to
a heavy-weight tag when the upstream ref does not; nevertheless i don't
really see a reason not to support this fallback.)

handle heavy-weight tags for upstream (SOFTWARE-3453)

---

osgbuild/fetch_sources.py

this has the effect of making sha1sum mandatory for non-scratch builds with cached upstream sources

always verify sha1sum if nocheck not specified (SOFTWARE-3787)

---

osgbuild/mock.py

mock 2.0's version is simply "2.0", not "2.0.0", so fix the
version-detecting regex to handle it.

Support mock version strings of different lengths

---

rpm/osg-build.spec

... and yes I know I _just_ added support for it.

Require mock < 2.0 to avoid build errors related to (attempted) use of DNF

---

osgbuild/constants.py
osgbuild/kojiinter.py

What it says on the tin.
This will let me get rid of the gross hack where I load the `koji` script as a library for the `watch_tasks()` function... stay tuned.

Use a newer Koji on CSL machines

---

data/promoter.ini

Extra dvers are off by default and have to be specified on the command like, like --el8

el8 support for osg-promote

---

osgbuild/promoter.py

The --no-elX and --elX options used the `append_const` action without specifying the const.
This was causing `None` to be appended instead of a dver.
(why did this ever work)

Fix argument parsing for dver selection  (SOFTWARE-4078)

---

osgbuild/kojiinter.py
rpm/osg-build.spec

As of koji 1.13, watch_tasks got moved into a separate library which I can import as normal.

Drop gross hack used for getting watch_tasks from the koji cli

---

osgbuild/mock.py

Doing el8 builds in osg-build mock sometimes fails with errors like
```
No available modular metadata for modular package 'perl-Carp-1.50-439.module_el8.3.0+406+78614513.noarch', it cannot be installed on the system
No available modular metadata for modular package 'perl-Encode-4:3.01-439.module_el8.3.0+406+78614513.x86_64', it cannot be installed on the system
No available modular metadata for modular package 'perl-Errno-1.30-451.module_el8.3.0+406+78614513.x86_64', it cannot be installed on the system
...
Error: No available modular metadata for modular package
```
The fix for that is to add the `module_hotfixes=1` option to the `yum.conf` files generated by Koji. Mock configs generated by Koji for Koji builds are fine -- we set the `mock.yum.module_hotfixes=1` tag option in the EL8 …

Set module_hotfixes in mock config

---

osgbuild/constants.py
osgbuild/svn.py

[SOFTWARE-4411](https://opensciencegrid.atlassian.net/browse/SOFTWARE-4411)
Lets `osg-build koji --repo 3.5` work in `trunk` and lets `osg-build koji` (w/o the repo) work in `branches/osg-3.5` (once we create it).

Allow building from `trunk` branch to `osg-3.5-el*` targets and from `osg-3.5` branch to `osg-el*` targets

---

osgbuild/svn.py

With `master`
```
blin@blin-work:~/pkgs/redhat/branches/osg-3.6/voms.el8$ osg-build koji .
-------------------------------------------------------------------------------
SVN error: Forbidden to build from branches/osg-3.6 branch into osg-el7 target
-------------------------------------------------------------------------------
blin@blin-work:~/pkgs/redhat/branches/3.6-upcoming/osg-flock$ osg-build koji --repo upcoming .
-------------------------------------------------------------------------------
SVN error: Forbidden to build from branches/3.6-upcoming branch into osg-upcoming-el8 target
-------------------------------------------------------------------------------
```
With this branch:
```
blin@blin-work:~/pkgs/redhat/branches/3.6-upcoming/osg-flock$ osg-build koji --repo upcoming . …
```

Make OSG 3.6 the default target release series (SOFTWARE-5208)

---

fetch-dot-source

mostly because /usr/bin/python is not available on many places anymore.

Switch fetch-dot-source to Python3

---

data/osg-koji-home.conf
data/osg-koji-site.conf

- Use a constant for the server instead of hardcoding it
- Use https
- Fix the "topurl" which is used for Koji file access -- this was breaking `koji download-build`
- Drop unused "ca" option
- Bring osg-koji-site.conf up to date with osg-koji-home.conf

Fix default Koji configs:

---

osgbuild/main.py

Needed for `osg-build koji` to recognize `--repo 23-internal` as valid arguments.

Match tags for osg-23-internal

---

Makefile
osg-build-test
osgbuild/constants.py
osgbuild/fetch_sources.py
osgbuild/git.py
osgbuild/mock.py
osgbuild/svn.py
osgbuild/test/common.py
osgbuild/test/test_osgbuild.py
osgbuild/test/test_osgbuild_koji.py

Drop support for "trunk" and unversioned "upcoming", which are now "branches/osg-3.5" and "branches/3.5-upcoming".  Fix the tests that used trunk or upcoming, and add a bunch of other test fixes while I'm at it.
Tests using `koji` and `mock` were split off into a separate file, and the executable `osg-build-test` is now a script that calls the other tests.  koji tests are skipped if you don't have koji installed or your ~/.osg-koji is not set up.

Drop trunk, fix tests

---

osgbuild/promoter.py

Always require that you specify a route with -r or --route. We don't want to have to worry about changing the default on people as new release series happen.

Drop 'default' promotion route

---

osgbuild/promoter.py
osgbuild/test/test_osgpromote.py

the way I'm configuring the logging when it's called as a script feels like a hack; I'll revisit it later

Add some logging to osg-promote

---

data/promoter.ini
osgbuild/promoter.py
osgbuild/test/test_osgpromote.py

SOFTWARE-5637
This adds config to promoter.ini listing the required key(s) for each promotion route, and code to promoter.py to check signatures and, if necessary, run osg-sign to sign RPMs.
There was some cleanup work along the way. I promoter.Configuration is now a subclass of utils.IniConfiguration; the ini files are immediately loaded when creating the object, you don't have to call load_inifile() separately. You need to have created an osg_sign.SigningKeysConfig before creating the Configuration object. Parsing has been split up into multiple methods to make the flow cleaner. If there are multiple errors in a config section, they will all be reported instead of exiting at the first one.
The Route class was changed from a namedtuple to a regular object so I could add a method to …

osg-promote: validate signatures and try to sign packages

---

osgbuild/kojiinter.py

https://stackoverflow.com/questions/47564710/regular-expression-split-futurewarning-split-requires-a-non-empty-pattern-m

Fix "split() requires non-empty pattern match" warning

---

osgbuild/osg_sign.py

Some RPMs are big and /var/tmp has more room.

Use /var/tmp as the default temp directory for downloading RPMs to sign

---

data/promoter.ini
data/signing_keys.ini
osgbuild/constants.py
osgbuild/git.py

INF-1662
These have the usual 3-part (development, testing, release) structure. There's no prerelease so the 'chtc-release' promotion route goes directly from testing to release.
The default is el9 only but el8 is also available (pass --el8 when building or promoting).
CHTC repos use the https://github.com/CHTC/packaging.git repo to build from.  Since the ".git" at the end is optional, I made some changes to "normalize" the remote URL for our various checks.

Add support for "CHTC" repos

---

osgbuild/constants.py
osgbuild/main.py

- Update `repo_hints()` in main.py to allow the new `osg-23-elX-{empty|contrib}` build targets as arguments to `osg-build`
Additional configuration steps required in koji are documented in JIRA: https://opensciencegrid.atlassian.net/browse/SOFTWARE-5702

SOFTWARE-5702: OSG 23 empty/contrib build targets
